name: Package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - uses: wangsijie/setup-v2ray@v1
      with:
        config-base64: ${{ secrets.V2RAY_CONFIG }}
    
    - name: Login to registry
      uses: docker/login-action@v1
      env:
        http_proxy: http://127.0.0.1:1080
        https_proxy: http://127.0.0.1:1080
        all_proxy: socks5://127.0.0.1:1081
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.CR_USERNAME }}
        password: ${{ secrets.CR_PASSWORD }}
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        http_proxy: http://127.0.0.1:1080
        https_proxy: http://127.0.0.1:1080
        all_proxy: socks5://127.0.0.1:1081
      with:
        context: ./
        push: true
        tags: registry.cn-shanghai.aliyuncs.com/meeyou/blog:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
    
    - name: deploy
      run: curl ${{ secrets.DEPLOY_HOOK_URI }}
